version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8080:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: motorcycles
      POSTGRES_USER: motorcycles
      POSTGRES_PASSWORD: motorcycles$#@!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
